import { OpportunityInfo } from "./types";

export const dummyOpportunities: OpportunityInfo[] = [
  {
    numero_projeto: 1,
    numero_adicional: 101,
    status: "Em Andamento",
    descricao_projeto: "Construção de um prédio comercial de alto padrão.",
    cliente: "Empresa Alpha",
    data_cadastro: "2024-11-01",
    data_solicitacao: "2024-11-02",
    data_envio_proposta: "2024-11-05",
    data_fechamento: "",
    vendedor: "Carlos Silva",
    gerente: "Ana Oliveira",
    valor_faturamento_dolphin: 120000,
    valor_faturamento_direto: 80000,
    valor_total: 200000,
  },
  {
    numero_projeto: 2,
    numero_adicional: 102,
    status: "Concluído",
    descricao_projeto: "Reforma de escola municipal.",
    cliente: "Prefeitura Beta",
    data_cadastro: "2024-10-15",
    data_solicitacao: "2024-10-18",
    data_envio_proposta: "2024-10-20",
    data_fechamento: "2024-11-01",
    vendedor: "Maria Santos",
    gerente: "Pedro Alves",
    valor_faturamento_dolphin: 50000,
    valor_faturamento_direto: 25000,
    valor_total: 75000,
  },
  {
    numero_projeto: 3,
    numero_adicional: 103,
    status: "Cancelado",
    descricao_projeto: "Desenvolvimento de software personalizado.",
    cliente: "Startup Gamma",
    data_cadastro: "2024-09-10",
    data_solicitacao: "2024-09-12",
    data_envio_proposta: "2024-09-15",
    data_fechamento: "",
    vendedor: "Fernando Rocha",
    gerente: "Clara Mendes",
    valor_faturamento_dolphin: 0,
    valor_faturamento_direto: 0,
    valor_total: 0,
  },
  {
    numero_projeto: 4,
    numero_adicional: 104,
    status: "Aguardando Aprovação",
    descricao_projeto: "Fornecimento de equipamentos industriais.",
    cliente: "Indústria Delta",
    data_cadastro: "2024-08-20",
    data_solicitacao: "2024-08-22",
    data_envio_proposta: "2024-08-25",
    data_fechamento: "",
    vendedor: "Juliana Nogueira",
    gerente: "Rafael Souza",
    valor_faturamento_dolphin: 40000,
    valor_faturamento_direto: 10000,
    valor_total: 50000,
  },
  {
    numero_projeto: 5,
    numero_adicional: 105,
    status: "Em Andamento",
    descricao_projeto: "Construção de um complexo esportivo.",
    cliente: "Prefeitura Epsilon",
    data_cadastro: "2024-07-01",
    data_solicitacao: "2024-07-03",
    data_envio_proposta: "2024-07-05",
    data_fechamento: "",
    vendedor: "Lucas Ferreira",
    gerente: "Beatriz Ramos",
    valor_faturamento_dolphin: 180000,
    valor_faturamento_direto: 70000,
    valor_total: 250000,
  },
];
