import { OpportunityInfo } from "./types";

export const dummyOpportunities: OpportunityInfo[] = [
  {
    numero_projeto: "001",
    numero_adicional: "A001",
    status: "Em Andamento",
    descricao_projeto: "Construção de um prédio comercial de alto padrão.",
    cliente: "Empresa Alpha",
    data_cadastro: "2024-11-01",
    data_solicitacao: "2024-11-02",
    data_envio_proposta: "2024-11-05",
    data_fechamento: "",
    vendedor: "Carlos Silva",
    gerente: "Ana Oliveira",
    coordenador: "João Pereira",
  },
  {
    numero_projeto: "002",
    numero_adicional: "A002",
    status: "Concluído",
    descricao_projeto: "Reforma de escola municipal.",
    cliente: "Prefeitura Beta",
    data_cadastro: "2024-10-15",
    data_solicitacao: "2024-10-18",
    data_envio_proposta: "2024-10-20",
    data_fechamento: "2024-11-01",
    vendedor: "Maria Santos",
    gerente: "Pedro Alves",
    coordenador: "Laura Costa",
  },
  {
    numero_projeto: "003",
    numero_adicional: "A003",
    status: "Cancelado",
    descricao_projeto: "Desenvolvimento de software personalizado.",
    cliente: "Startup Gamma",
    data_cadastro: "2024-09-10",
    data_solicitacao: "2024-09-12",
    data_envio_proposta: "2024-09-15",
    data_fechamento: "",
    vendedor: "Fernando Rocha",
    gerente: "Clara Mendes",
    coordenador: "Paulo Lima",
  },
  {
    numero_projeto: "004",
    numero_adicional: "A004",
    status: "Aguardando Aprovação",
    descricao_projeto: "Fornecimento de equipamentos industriais.",
    cliente: "Indústria Delta",
    data_cadastro: "2024-08-20",
    data_solicitacao: "2024-08-22",
    data_envio_proposta: "2024-08-25",
    data_fechamento: "",
    vendedor: "Juliana Nogueira",
    gerente: "Rafael Souza",
    coordenador: "Sofia Almeida",
  },
  {
    numero_projeto: "005",
    numero_adicional: "A005",
    status: "Em Andamento",
    descricao_projeto: "Construção de um complexo esportivo.",
    cliente: "Prefeitura Epsilon",
    data_cadastro: "2024-07-01",
    data_solicitacao: "2024-07-03",
    data_envio_proposta: "2024-07-05",
    data_fechamento: "",
    vendedor: "Lucas Ferreira",
    gerente: "Beatriz Ramos",
    coordenador: "Tiago Oliveira",
  },
  {
    numero_projeto: "006",
    numero_adicional: "A006",
    status: "Concluído",
    descricao_projeto: "Instalação de painéis solares.",
    cliente: "Empresa Zeta",
    data_cadastro: "2024-06-10",
    data_solicitacao: "2024-06-12",
    data_envio_proposta: "2024-06-15",
    data_fechamento: "2024-06-30",
    vendedor: "Mariana Costa",
    gerente: "Diego Rocha",
    coordenador: "Alice Farias",
  },
  {
    numero_projeto: "007",
    numero_adicional: "A007",
    status: "Pendente",
    descricao_projeto: "Automação de processos industriais.",
    cliente: "Indústria Theta",
    data_cadastro: "2024-05-05",
    data_solicitacao: "2024-05-07",
    data_envio_proposta: "2024-05-10",
    data_fechamento: "",
    vendedor: "Bruno Martins",
    gerente: "Isabela Freitas",
    coordenador: "Ricardo Lopes",
  },
  {
    numero_projeto: "008",
    numero_adicional: "A008",
    status: "Em Negociação",
    descricao_projeto: "Construção de um hospital.",
    cliente: "Governo Federal",
    data_cadastro: "2024-04-15",
    data_solicitacao: "2024-04-18",
    data_envio_proposta: "2024-04-20",
    data_fechamento: "",
    vendedor: "Camila Silva",
    gerente: "Eduardo Pereira",
    coordenador: "Luana Barros",
  },
  {
    numero_projeto: "009",
    numero_adicional: "A009",
    status: "Concluído",
    descricao_projeto: "Modernização de infraestrutura de TI.",
    cliente: "Banco Omicron",
    data_cadastro: "2024-03-01",
    data_solicitacao: "2024-03-05",
    data_envio_proposta: "2024-03-07",
    data_fechamento: "2024-03-20",
    vendedor: "Gustavo Mendes",
    gerente: "Fernanda Silva",
    coordenador: "Joana Dias",
  },
  {
    numero_projeto: "010",
    numero_adicional: "A010",
    status: "Em Andamento",
    descricao_projeto: "Construção de terminal logístico.",
    cliente: "Empresa Lambda",
    data_cadastro: "2024-02-10",
    data_solicitacao: "2024-02-12",
    data_envio_proposta: "2024-02-15",
    data_fechamento: "",
    vendedor: "Patrícia Duarte",
    gerente: "Marcelo Nunes",
    coordenador: "Daniela Gomes",
  },
];
